/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "I2C_SDA_aliases.h"
#include "I2C_SDA.h"
#include "I2C_SCL_aliases.h"
#include "I2C_SCL.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "UART.h"
#include "RTC_INTR.h"
#include "RTC_INTR_PIN_aliases.h"
#include "RTC_INTR_PIN.h"
#include "UART_RX_aliases.h"
#include "UART_RX.h"
#include "DEBOUNCE_CLK.h"
#include "BTN_INPUT_aliases.h"
#include "BTN_INPUT.h"
#include "BTN_RIGHT_INTR.h"
#include "BTN_LEFT_INTR.h"
#include "BTN_ENTER_INTR.h"
#include "UART_RX_INTR.h"
#include "SENSOR_TIMER.h"
#include "SENSOR_1MS.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

